In [1]:
import pandas as pd

In [8]:
df=pd.read_csv('companies.csv')

<h1><b>Q:1  HOW BIG IS DATA?</b></h1>

In [10]:
df.shape

(2000, 7)

<h1><b>Q:2 HOW DOES THE DATA LOOK LIKE?</B></h1>

In [11]:
df.head()

,Company,Reviews,Company_Type,Head_Office,Salaries,Interviews,Jobs
0,TCS,(1.2L),IT Services & Consulting,Bengaluru +476 other locations,10.4L,11.4k,5k
1,Accenture,(75.8k),IT Services & Consulting,Bengaluru +279 other locations,7.3L,9.5k,19.9k
2,Wipro,(66.8k),IT Services & Consulting,Hyderabad +390 other locations,4.9L,7k,104
3,Cognizant,(63.1k),IT Services & Consulting,Hyderabad +252 other locations,6.1L,6.6k,973
4,Capgemini,(55.2k),IT Services & Consulting,Bengaluru +204 other locations,5L,5.7k,2.3k

In [15]:
df.sample(5)

,Company,Reviews,Company_Type,Head_Office,Salaries,Interviews,Jobs
53,Paytm,(9.6k),FinTech,Noida +434 other locations,35.7k,922,1.2k
670,IFB,(1.6k),Consumer Electronics & Appliances,Bengaluru +180 other locations,5.6k,126,23
106,Manappuram Finance,(6k),NBFC,Bengaluru +674 other locations,9.8k,239,7
1383,Ksb Pumps,(802),Industrial Machinery,Pune +40 other locations,3.5k,59,140
1375,Hilti,(805),Industrial Machinery,Gurugram +48 other locations,3.8k,75,14

<h1><b>Q:3 what is the data type of column?</b></h1>

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company       2000 non-null   object
 1   Reviews       2000 non-null   object
 2   Company_Type  2000 non-null   object
 3   Head_Office   1992 non-null   object
 4   Salaries      2000 non-null   object
 5   Interviews    2000 non-null   object
 6   Jobs          2000 non-null   object
dtypes: object(7)
memory usage: 109.5+ KB

<h1><b>Q:4  Are there any missing value?</b></h1>

In [16]:
df.isnull().sum()

Company         0
Reviews         0
Company_Type    0
Head_Office     8
Salaries        0
Interviews      0
Jobs            0
dtype: int64

<h1><b>Q:5  How does the data look mathematically ?</b></h1>

In [17]:
df.describe()

,Company,Reviews,Company_Type,Head_Office,Salaries,Interviews,Jobs
count,2000,2000,2000,1992,2000,2000,2000
unique,1996,486,82,1308,340,471,287
top,Hamilton Housewares,(1.1k),IT Services & Consulting,Bengaluru +19 other locations,2.8k,50,--
freq,2,94,253,12,47,23,385

<h1><b>Q:6  Are there any duplicte value?</b></h1>

In [20]:
df.duplicated().sum()

np.int64(4)

<h1><b>Q:7  How is the corelation between column?</b></h1>

In [24]:
df.select_dtypes(include='number').corr()

Empty DataFrame
Columns: []
Index: []