In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv

In [3]:
df=pd.read_csv('/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv')

In [6]:
df.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
476,57,1,0,165,289,1,0,124,0,1.0,1,3,3,0
873,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
423,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
78,52,1,1,134,201,0,1,158,0,0.8,2,1,2,1
349,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [9]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [12]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [13]:

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.6439024390243903
Accuracy of Decision Trees 0.6585365853658537

In [15]:
confusion_matrix(y_test,y_pred1)

array([[65, 40],
       [33, 67]])

In [16]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  65  40
1  33  67

In [17]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  69  36
1  34  66

In [18]:

result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [19]:

result.sample(10)

      Actual Label  Logistic Regression Prediction  Decision Tree Prediction
356              0                               0                         0
376              1                               0                         0
510              1                               1                         1
1000             0                               0                         1
272              1                               1                         1
529              1                               0                         1
577              0                               0                         0
146              1                               1                         1
646              0                               1                         1
456              0                               1                         1

In [20]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [21]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  65  40
1  33  67
--------------------------------------------------
Precision -  0.6261682242990654
Recall -  0.67
F1 score -  0.6473429951690821

In [22]:
precision_score(y_test,y_pred1,average=None)

array([0.66326531, 0.62616822])

In [23]:
precision_score(y_test,y_pred2,average=None)

array([0.66990291, 0.64705882])

In [24]:
recall_score(y_test,y_pred2,average=None)

array([0.65714286, 0.66      ])