In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
df=pd .read_csv('covid_toy.csv')

In [7]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [10]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [11]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=2)

In [15]:
X_train

    age  gender  fever   cough       city
35   82  Female  102.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
84   69  Female   98.0  Strong     Mumbai
44   20    Male  102.0  Strong      Delhi
73   34    Male   98.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
43   22  Female   99.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata
72   83  Female  101.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi

[80 rows x 5 columns]

<h1></b>Aam zindagi<b></h1>

In [27]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [35]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [41]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [47]:


# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [56]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

<h1><b>mentors zindagi<b></h1>

In [57]:
from sklearn.compose import ColumnTransformer

In [68]:
transformer=ColumnTransformer(transformers=[
      ('tnf1',SimpleImputer(),['fever']),
      ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
      ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])

    
],remainder='passthrough')

In [69]:
transformer.fit_transform(X_train).shape

(80, 7)

In [72]:
transformer.fit_transform(X_test).shape

(20, 7)