<a href="https://colab.research.google.com/github/ayushmant908-web/machine_learning-100-Days/blob/main/Decision_tree_regressor_ml_day_61.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import r2_score

In [9]:
boston = fetch_openml(name='boston', version=1, as_frame=True)

df = boston.frame
df.head()

      CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
0  0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
1  0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
2  0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
3  0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
4  0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2

[5 rows x 14 columns]

In [10]:
df.column=boston.feature_names
df['MEDV']=boston.target

/tmp/ipykernel_1565/1886631803.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.column=boston.feature_names

In [11]:
df.head()

      CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
0  0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
1  0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
2  0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
3  0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
4  0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2

[5 rows x 14 columns]

In [12]:
X=df.iloc[:,0:13]
y=df.iloc[:,13]

In [14]:
from numpy.matrixlib import test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
rt=DecisionTreeRegressor(criterion='squared_error',max_depth=5)

In [19]:
rt.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=5)

In [20]:
y_pred=rt.predict(X_test)

In [21]:
r2_score(y_test,y_pred)

0.7224163455290411

<h1><b>Hypertuning pairamiter Tuing

In [30]:
param_grid={
    'max_depth':[2,4,6,8,None],
    'criterion':['absolute_error','squared_error','friedman_mse'],
    'min_samples_split':[0.25,0.5,1.0],
    'min_samples_leaf':[0.25,0.5,1.0]



}

In [31]:
reg=GridSearchCV(DecisionTreeRegressor(),param_grid=param_grid)

In [32]:
reg.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
225 fits failed out of a total of 675.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
225 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_leaf' parameter of DecisionTreeRegressor must be an int in the range [1, inf) or a float in the range (0.0, 1.0). Got 1.0 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.51957849 0.51957849 0.35809099 0.03165474 0.03165474 0.03165474
        nan        nan        nan 0.51957849 0.51957849 0.35809099
 0.03165474 0.03165474 0.03165474        nan        nan        nan
 0.51957849 0.51957849 0.35809099 0.03165474 0.03165474 0.03165474
        nan        nan        nan 0.51957849 0.51957849 0.35809099
 0.03165474 0.03165474 0.03165474        nan        nan        nan
 0.51957849 0.51957849 0.35809099 0.03165474 0.03165474 0.03165474
        nan        nan        nan 0.48853152 0.48853152 0.40413411
 0.05036885 0.05036885 0.05036885        nan        nan        nan
 0.48853152 0.48853152 0.40413411 0.05036885 0.05036885 0.05036885
        nan        nan        nan 0.48853152 0.48853152 0.40413411
 0.05036885 0.05036885 0.05036885        nan        nan        nan
 0.48853152 0.48853152 0.40413411 0.05036885 0.05036885 0.05036885
        nan        nan        nan 0.48853152 0.48853152 0.40413411
 0.05036885 0.05036885 0.05036885        nan        nan        nan
 0.48853152 0.48853152 0.40413411 0.05036885 0.05036885 0.05036885
        nan        nan        nan 0.48853152 0.48853152 0.40413411
 0.05036885 0.05036885 0.05036885        nan        nan        nan
 0.48853152 0.48853152 0.40413411 0.05036885 0.05036885 0.05036885
        nan        nan        nan 0.48853152 0.48853152 0.40413411
 0.05036885 0.05036885 0.05036885        nan        nan        nan
 0.48853152 0.48853152 0.40413411 0.05036885 0.05036885 0.05036885
        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['absolute_error', 'squared_error',
                                       'friedman_mse'],
                         'max_depth': [2, 4, 6, 8, None],
                         'min_samples_leaf': [0.25, 0.5, 1.0],
                         'min_samples_split': [0.25, 0.5, 1.0]})

In [34]:
reg.best_score_

np.float64(0.519578486418291)

In [35]:
reg.best_params_

{'criterion': 'absolute_error',
 'max_depth': 2,
 'min_samples_leaf': 0.25,
 'min_samples_split': 0.25}

<h1><b>Importance Features

In [36]:
for importance, name in sorted(zip(rt.feature_importances_, X_train.columns),reverse=True):
  print(name,importance)

RM 0.6292222501550587
LSTAT 0.216019203929161
DIS 0.07187288650018071
CRIM 0.03550388785641018
PTRATIO 0.01787104563443621
B 0.011905660139828158
INDUS 0.007018566233812773
AGE 0.006176126174364793
NOX 0.0044103733767475615
ZN 0.0
TAX 0.0
RAD 0.0
CHAS 0.0