<a href="https://colab.research.google.com/github/ayushmant908-web/machine_learning-100-Days/blob/main/navis_bais_all_probablitty_concept_ml_day_60s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd

In [36]:
df=pd.read_csv('/content/drive/MyDrive/play_tennis.csv')

In [37]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [38]:
df.drop(columns=['day'],inplace=True)

In [39]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [39]:
#problem=1
# outlook=sunny,temp=Hot, humidity=High, wind=Weak
#play or not play

In [ ]:
#soloution
#p(yes/sunny,hot,high,weak)=p(sunny/yes)+(Hot/yes)+p(high/yes)+p(weak/yes)+p(yes)
#p(no/sunny,hot,high,weak)=p(sunny/no)+(Hot/no)+p(high/no)+p(weak/no)+p(no)

#compare and decide using maximum a posterior rule

In [ ]:
#problem 2
#outlook=overcast,temp,cold,humidity=low,wind=weak
# play or not play

In [ ]:
#solution

#p(yes/overcast,cold,low,weak)=p(overcast/yes)+p(cold/yes)+p(low/yes)+p(weak/yes)+p(yes)
#p(no/overcast,cold,low,weak)=p(overcast/no)+p(cold/no)+p(low/no)+p(weak/no)+p(no))
#compare and decide using maximum a posterior rule

In [ ]:
#taswk performing

#1 traning
#2 lokup table(dictoniry)
# testing

In [ ]:
#p(yes)
#p(no)

In [40]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [41]:
py=9/14
pn=5/14

In [43]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [44]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [45]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [46]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [47]:
p_coll_no=1/5
p_hot_no=2/5
p_mild=2/5

p_coll_yes=3/9
p_hot_yes=2/9
p_mild_yes=4/9

In [48]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [49]:
p_high_no=4/5
p_normal_no=1/5

p_high_yes=3/9
p_normal_yes=6/9

In [50]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [51]:
p_humidity_no=4/5
P_humidity_no=1/5

p_humidity_yes=6/9
p_humidity_yes=3/9

In [52]:
#1 problem 1
# outlook=sunny,temp=Hot, humidity=High, wind=Weak

p_yes=(poy*p_hot_yes*p_high_yes*p_humidity_yes)*py
p_no=(poy*p_hot_no*p_high_no*p_humidity_no)*pn

In [53]:
print(p_yes)
print(p_no)

0.007054673721340387
0.040634920634920635