In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [12]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

<h1></b>one hot encoding using pandas<b></h1>

In [22]:
pd.get_dummies(df, columns=['fuel', 'owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

<h1></b>k-1 one hot encoding<b></h1>

In [75]:
pd.get_dummies(df, columns=['fuel', 'owner'],dtype=float,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Skoda,120000,370000,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Honda,140000,158000,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,Hyundai,127000,225000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Maruti,120000,130000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8124,Hyundai,119000,135000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
8125,Maruti,120000,382000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8126,Tata,25000,290000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8127,Tata,25000,290000,1.0,0.0,0.0,0.0,0.0,0.0,0.0

<h1></b>one hot encoding using sklearn<b></h1>

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [77]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [110]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

X_train_new = ohe.fit_transform(
    X_train[['fuel', 'owner']]
).toarray()

X_test_new = ohe.transform(
    X_test[['fuel', 'owner']]
).toarray()

X_train_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(6502, 9))

In [117]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [114]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

ohe = OneHotEncoder(
    drop='first',
    sparse_output=False,
    dtype=np.int32
)

X_train_new = ohe.fit_transform(
    X_train[['fuel', 'owner']]
)

X_test_new = ohe.transform(
    X_test[['fuel', 'owner']]
)

X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [115]:
X_train_new.shape

(6502, 7)

In [118]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

<h1></b>one hot encoding with top categories<b></h1>

In [121]:
counts=df['brand'].value_counts()

In [123]:
df['brand'].nunique()
thresold=100

In [126]:
repl=counts[counts<=thresold].index

In [134]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
527,0,0,0,1,0,0,0,0,0,0,0,0,0
3907,0,0,0,0,0,0,0,0,0,0,0,0,1
123,0,0,0,0,0,0,1,0,0,0,0,0,0
4872,0,0,0,0,0,0,0,0,0,0,0,0,1
3237,0,0,0,0,0,0,0,0,0,0,0,0,1