<a href="https://colab.research.google.com/github/ayushmant908-web/machine_learning-100-Days/blob/main/Voting_regressor_ml_day_63.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
import pandas as pd

In [53]:
from sklearn.datasets import fetch_openml
boston = fetch_openml(
    name='boston',
    version=1,
    as_frame=True
)

In [54]:
df=boston.frame

In [55]:
df.shape

(506, 14)

In [56]:
X=df.iloc[:,0:13]
y=df.iloc[:,-1]

In [57]:
X.shape

(506, 13)

In [58]:
y.shape

(506,)

In [59]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88

In [77]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [78]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

In [79]:
lr=LinearRegression()
dt=DecisionTreeRegressor()
svr=SVR()

In [80]:
estimators=[('lr',lr),('dt',dt),('svr',svr)]

In [81]:
for estimator in estimators:
  x=cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(x),2))

lr 0.18
dt -0.34
svr -0.41

In [64]:
from sklearn.ensemble import VotingRegressor

In [69]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [70]:
vr=VotingRegressor(estimators)
scorers=cross_val_score(vr,X,y,cv=10,scoring='r2')
print('voting_regrtessor',np.round(np.mean(scorers),2))

voting_regrtessor 0.46

In [71]:
for i in range(1,4):
  for j in range(1,4):
    for k in range(1,4):
      vr = VotingRegressor(estimators,weights=[i,j,k])
      scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
      print("For i={},j={},k={}".format(i,j,k),np.round(np.mean(scores),2))

For i=1,j=1,k=1 0.39
For i=1,j=1,k=2 0.37
For i=1,j=1,k=3 0.27
For i=1,j=2,k=1 0.43
For i=1,j=2,k=2 0.43
For i=1,j=2,k=3 0.29
For i=1,j=3,k=1 0.38
For i=1,j=3,k=2 0.4
For i=1,j=3,k=3 0.3
For i=2,j=1,k=1 0.46
For i=2,j=1,k=2 0.42
For i=2,j=1,k=3 0.36
For i=2,j=2,k=1 0.45
For i=2,j=2,k=2 0.44
For i=2,j=2,k=3 0.41
For i=2,j=3,k=1 0.38
For i=2,j=3,k=2 0.45
For i=2,j=3,k=3 0.43
For i=3,j=1,k=1 0.44
For i=3,j=1,k=2 0.44
For i=3,j=1,k=3 0.38
For i=3,j=2,k=1 0.46
For i=3,j=2,k=2 0.45
For i=3,j=2,k=3 0.44
For i=3,j=3,k=1 0.44
For i=3,j=3,k=2 0.43
For i=3,j=3,k=3 0.45

In [67]:
X.dtypes

CRIM        float64
ZN          float64
INDUS       float64
CHAS       category
NOX         float64
RM          float64
AGE         float64
DIS         float64
RAD        category
TAX         float64
PTRATIO     float64
B           float64
LSTAT       float64
dtype: object

In [68]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [72]:
# using the same algorithm
dv1=DecisionTreeRegressor(max_depth=1)
dv2=DecisionTreeRegressor(max_depth=2)
dv3=DecisionTreeRegressor(max_depth=3)
dv4=DecisionTreeRegressor(max_depth=4)
dv5=DecisionTreeRegressor(max_depth=None)

In [74]:
estimators=[('dv1',dv1),('dv2',dv2),('dv3',dv3),('dv4',dv4),('dv5',dv5)]

In [75]:

for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

dv1 -0.85
dv2 -0.07
dv3 -0.11
dv4 -0.02
dv5 -0.3

In [76]:
vc=VotingRegressor(estimators)
scores=cross_val_score(vc,X,y,scoring='r2',cv=10)
print('voting_regressor',np.round(np.mean(scores),2))

voting_regressor 0.16