In [1]:
print('hello')

hello

<h1><b>working with json<b></h1>

In [2]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:

pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.0386
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.6760
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.8680
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,3.8700
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,2.5100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.1720
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.1920
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-02,1782950401,0.2820

<h1><b>working with SQL<b><h/1>

In [4]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 896.1 kB/s eta 0:00:13
     -- ------------------------------------ 0.8/11.9 MB 907.4 kB/s eta 0:00:13
     --- ----------------------------------- 1.0/11.9 MB 995.1 kB/s eta 0:00:11
     ---- ----------------------------------- 1.3/11.9 MB 1.1 MB/s eta 0:00:11
     ----- ---------------------------------- 1.6/11.9 MB 1.1 MB/s eta 0:00:10
     ----- ---------------------------------- 1.6/11.9 MB 1.1 MB/s eta 0:00:10
     ------ -------------------------------- 1.8/11.9 MB 986.2 kB/s eta 0:00:11
     ------- -------------------------------- 2.1/11.9 MB 1.0 MB/s eta 0:00:10
     ------- -------------------------------- 2.4/11.9 MB 1.1 MB/s eta 0:00:10
     -------- ------------------------------- 2.6/11.9 MB 1.1 MB/s eta 0:00:09
     --------- ------------------------------ 2.9/11.9 MB 1.1 MB/s eta 0:00:09
     ---------- ----------------------------- 3.1/11.9 MB 1.1 MB/s eta 0:00:08
     ----------- ---------------------------- 3.4/11.9 MB 1.1 MB/s eta 0:00:08
     ------------ --------------------------- 3.7/11.9 MB 1.1 MB/s eta 0:00:08
     ------------- -------------------------- 3.9/11.9 MB 1.1 MB/s eta 0:00:08
     -------------- ------------------------- 4.2/11.9 MB 1.1 MB/s eta 0:00:07
     --------------- ------------------------ 4.5/11.9 MB 1.1 MB/s eta 0:00:07
     --------------- ------------------------ 4.7/11.9 MB 1.1 MB/s eta 0:00:07
     ---------------- ----------------------- 5.0/11.9 MB 1.1 MB/s eta 0:00:07
     ----------------- ---------------------- 5.2/11.9 MB 1.1 MB/s eta 0:00:06
     ------------------ --------------------- 5.5/11.9 MB 1.2 MB/s eta 0:00:06
     ------------------- -------------------- 5.8/11.9 MB 1.2 MB/s eta 0:00:06
     -------------------- ------------------- 6.0/11.9 MB 1.2 MB/s eta 0:00:06
     --------------------- ------------------ 6.3/11.9 MB 1.2 MB/s eta 0:00:05
     ---------------------- ----------------- 6.6/11.9 MB 1.1 MB/s eta 0:00:05
     ----------------------- ---------------- 6.8/11.9 MB 1.1 MB/s eta 0:00:05
     ----------------------- ---------------- 7.1/11.9 MB 1.2 MB/s eta 0:00:05
     ------------------------ --------------- 7.3/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.6/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.1/11.9 MB 1.2 MB/s eta 0:00:04
     ---------------------------- ----------- 8.4/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 8.9/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 9.2/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.2 MB/s eta 0:00:03
     -------------------------------- ------- 9.7/11.9 MB 1.2 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.2 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.2 MB/s eta 0:00:02
     ----------------------------------- ---- 10.5/11.9 MB 1.2 MB/s eta 0:00:02
     ------------------------------------ --- 10.7/11.9 MB 1.2 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.2 MB/s  0:00:10
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=9f3ab6a693e72f97f8948bed07cd98ae82c1cca92f960a75069861124702bb73
  Stored in directory: c:\users\francis d'souza\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [5]:
import mysql.connector

In [7]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",      # XAMPP me default password blank hota hai
    database="world"  # Apne database ka naam likhiye
)

print("Database Connected Successfully!")

Database Connected Successfully!

In [8]:
pd.read_sql_query("select*from city",conn)

C:\Users\Francis D'Souza\AppData\Local\Temp\ipykernel_11788\754812427.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select*from city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [12]:
pd.read_sql_query("select*from country",conn)

C:\Users\Francis D'Souza\AppData\Local\Temp\ipykernel_11788\1759507201.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select*from country",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW